### ISSUE TITLE
處理實際語句連詞

### ISSUE THREAD

**Issue by sih4sing5hong5** [sih4sing5hong5/tai5-uan5_gian5-gi2_kang1-ku7#101]
傷歹設計，用kenlm就好，台掉實際語句連詞

愛閣改好
`試驗/斷詞/辭典連詞斷詞試驗.py`
`試驗/斷詞/連詞揀集內組試驗.py`
的試驗

**Comment by sih4sing5hong5** [comment]
留咧試驗用
共`感覺`佮`權重`提掉

出現的錯誤
```python3
======================================================================
FAIL: test_看機率選詞 (斷詞.Test語言模型揀集內組單元試驗.語言模型揀集內組單元試驗)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tshau/git/tai5_uan5_gian5_gi2_kang1_ku7/試驗/斷詞/Test語言模型揀集內組單元試驗.py", line 85, in test_看機率選詞
    self.assertEqual(鞋的結果, 我鞋鞋仔)
AssertionError: 句：[集：[16 chars]]], 集：[組：[詞：[字：鞋 e5]]], 集：[組：[詞：[字：的 e5]]], 集：[組：[詞：[字：仔 a2]]]] != 句：[集：[16 chars]]], 集：[組：[詞：[字：鞋 e5]]], 集：[組：[詞：[字：鞋 e5]]], 集：[組：[詞：[字：仔 a2]]]]

======================================================================
FAIL: test_選無仝長度的集 (斷詞.Test語言模型揀集內組單元試驗.語言模型揀集內組單元試驗)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tshau/git/tai5_uan5_gian5_gi2_kang1_ku7/試驗/斷詞/Test語言模型揀集內組單元試驗.py", line 153, in test_選無仝長度的集
    self.assertLess(分數, 0.0)
AssertionError: 0.0 not less than 0.0
```
